import {
  faClipboardCheck,
  faComments,
  faPen,
  faUserCheck,
  faEye,
  faFileAlt,
  faChalkboardTeacher,
  faMapMarkedAlt,
} from "@fortawesome/free-solid-svg-icons";
import { Course, Lesson } from "../types";

export const cadastralSurveyCourse: Course = {
  id: "cadastral-survey",
  name: "Cadastral Survey Course",
  description:
    "Comprehensive training in cadastral survey techniques and land parcel mapping",
  weeks: 7,
  lessons: {
    1: {
      title: "Class 1",
      title1: "Reconnaissance Documentation Tools",
      objectives: [
        "Identify cadastral survey tools",
        "Utilize land registry documents",
        "Prepare survey documentation",
        "Apply legal requirements in surveys",
      ],
      content: [
        "Field documentation: notebooks, pens",
        "Calculation tools: calculators",
        "Map interpretation: scale rules",
        "Land registry documents: survey plans, index maps",
        "Folio registers and official land searches",
      ],
      practical: "Document handling exercise",
      assessments: [{ icon: faEye, label: "Direct observation" }],
      type: "theory",
    },
    2: {
      title: "Class 2",
      title1: "Site Analysis and Control Planning",
      objectives: [
        "Analyze site characteristics",
        "Identify optimal control points",
        "Evaluate parcel boundaries",
        "Document site conditions",
      ],
      content: [
        "Topographical feature assessment",
        "Boundary identification techniques",
        "Control point selection criteria",
        "Access and terrain evaluation",
        "Preliminary sketch preparation",
      ],
      practical: "Field reconnaissance exercise",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faComments, label: "Oral questioning" },
        { icon: faPen, label: "Written tests" },
      ],
      type: "practical",
    },
    3: {
      title: "Class 3",
      title1: "Reconnaissance Reporting",
      objectives: [
        "Compile reconnaissance findings",
        "Structure cadastral reports",
        "Analyze boundary evidence",
        "Propose survey methodology",
      ],
      content: [
        "Report format and legal standards",
        "Boundary evidence documentation",
        "Conflict identification techniques",
        "Methodology justification",
        "Risk assessment documentation",
      ],
      practical: "Report drafting session",
      assessments: [
        { icon: faPen, label: "Written tests" },
        { icon: faUserCheck, label: "Practicals" },
      ],
      type: "theory",
    },
    4: {
      title: "Class 4",
      title1: "Control Point Establishment Tools",
      objectives: [
        "Select appropriate monumentation tools",
        "Prepare control marking equipment",
        "Apply cadastral standards",
        "Implement safety procedures",
      ],
      content: [
        "Permanent monumentation tools",
        "Temporary marking equipment",
        "Cadastral accuracy standards",
        "Tool maintenance protocols",
        "Legal compliance requirements",
      ],
      practical: "Equipment preparation demonstration",
      assessments: [{ icon: faEye, label: "Direct observation" }],
      type: "theory",
    },
    5: {
      title: "Class 5",
      title1: "Control Point Identification",
      objectives: [
        "Locate existing cadastral marks",
        "Verify monument authenticity",
        "Record control point details",
        "Resolve monument conflicts",
      ],
      content: [
        "Monument identification techniques",
        "Cadastral mark verification",
        "Conflict resolution strategies",
        "Field documentation standards",
        "Historical record correlation",
      ],
      practical: "Field identification exercise",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "practical",
    },
    6: {
      title: "Class 6",
      title1: "Control Establishment Methods",
      objectives: [
        "Execute traverse surveys",
        "Apply GNSS positioning techniques",
        "Select appropriate establishment methods",
        "Ensure legal accuracy standards",
      ],
      content: [
        "Traverse survey procedures",
        "Static GNSS methods",
        "Method selection criteria",
        "Cadastral accuracy requirements",
        "Error minimization techniques",
      ],
      practical: "Method comparison demonstration",
      assessments: [
        { icon: faPen, label: "Written tests" },
        { icon: faUserCheck, label: "Practicals" },
      ],
      type: "theory",
    },
    7: {
      title: "Class 7",
      title1: "Advanced Control Methods",
      objectives: [
        "Perform triangulation surveys",
        "Conduct precise leveling",
        "Execute trilateration",
        "Apply advanced geometric techniques",
      ],
      content: [
        "Triangulation network design",
        "Precise leveling procedures",
        "Trilateration methodologies",
        "Geometric computations",
        "Network adjustment principles",
      ],
      practical: "Advanced method demonstration",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    8: {
      title: "Class 8",
      title1: "Control Point Monumentation",
      objectives: [
        "Install permanent monuments",
        "Apply cadastral monument standards",
        "Verify position accuracy",
        "Document monument details",
      ],
      content: [
        "Monument types and applications",
        "Installation best practices",
        "Position verification techniques",
        "As-built documentation",
        "Long-term preservation methods",
      ],
      practical: "Field monumentation exercise",
      assessments: [
        { icon: faUserCheck, label: "Practicals" },
        { icon: faPen, label: "Written tests" },
      ],
      type: "practical",
    },
    9: {
      title: "Class 9",
      title1: "Boundary Survey Equipment",
      objectives: [
        "Select boundary survey tools",
        "Prepare instruments for parcel surveys",
        "Apply legal measurement standards",
        "Maintain boundary equipment",
      ],
      content: [
        "Total stations for boundary work",
        "GNSS receivers for cadastral surveys",
        "Specialized measurement tools",
        "Legal compliance requirements",
        "Equipment calibration standards",
      ],
      practical: "Equipment setup demonstration",
      assessments: [{ icon: faEye, label: "Direct observation" }],
      type: "theory",
    },
    10: {
      title: "Class 10",
      title1: "Boundary Data Collection",
      objectives: [
        "Collect accurate boundary evidence",
        "Measure parcel dimensions",
        "Record corner positions",
        "Verify historical boundaries",
      ],
      content: [
        "Boundary evidence collection",
        "Corner measurement techniques",
        "Documentation standards",
        "Historical record reconciliation",
        "Discrepancy resolution methods",
      ],
      practical: "Field boundary survey",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "practical",
    },
    11: {
      title: "Class 11",
      title1: "Beacon Placement and Monumentation",
      objectives: [
        "Install boundary beacons",
        "Apply permanent monumentation",
        "Verify beacon positions",
        "Document boundary marks",
      ],
      content: [
        "Beacon types and applications",
        "Placement accuracy standards",
        "Monumentation best practices",
        "Position verification methods",
        "Legal documentation requirements",
      ],
      practical: "Beacon installation exercise",
      assessments: [
        { icon: faUserCheck, label: "Practicals" },
        { icon: faPen, label: "Written tests" },
      ],
      type: "practical",
    },
    12: {
      title: "Class 12",
      title1: "Cadastral Plan Preparation Methods",
      objectives: [
        "Apply cadastral drafting standards",
        "Select appropriate preparation methods",
        "Interpret survey regulations",
        "Design parcel plans",
      ],
      content: [
        "Manual drafting techniques",
        "Digital workflow options",
        "Legal symbolization standards",
        "Scale and annotation requirements",
        "Quality assurance protocols",
      ],
      practical: "Drafting method demonstration",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faComments, label: "Group discussions" },
      ],
      type: "theory",
    },
    13: {
      title: "Class 13",
      title1: "Digital Cadastral Mapping Tools",
      objectives: [
        "Operate cadastral GIS software",
        "Apply CAD tools for parcel mapping",
        "Prepare manual drafting materials",
        "Select appropriate production methods",
      ],
      content: [
        "AutoCAD for cadastral mapping",
        "ArcGIS parcel fabric applications",
        "QGIS cadastral tools",
        "Manual drafting: scales, pens, templates",
        "Hybrid digital-manual workflows",
      ],
      practical: "Software demonstration",
      assessments: [
        { icon: faFileAlt, label: "Projects" },
        { icon: faChalkboardTeacher, label: "Demonstrations" },
        { icon: faComments, label: "Group discussions" },
      ],
      type: "theory",
    },
    14: {
      title: "Class 14",
      title1: "Cadastral Plan Production",
      objectives: [
        "Process boundary survey data",
        "Compute parcel dimensions",
        "Generate legal cadastral plans",
        "Verify plan accuracy and compliance",
      ],
      content: [
        "Data processing workflows",
        "Boundary computation methods",
        "Plan layout and design",
        "Legal annotation standards",
        "Quality verification procedures",
      ],
      practical: "Complete plan production project",
      assessments: [
        { icon: faUserCheck, label: "Practical" },
        { icon: faFileAlt, label: "Project work" },
      ],
      type: "assessment",
    },
  },
  stats: {
    classes: 14,
    weeks: 7,
    categories: 4,
    exercises: "14+",
  },
  gradient: "linear-gradient(135deg, #f39c12, #e67e22)",
  icon: faMapMarkedAlt,
  modules: 7,
  hours: 28,
  category: "Cadastral Survey",
};
