import {
  faEye,
  faComments,
  faPen,
  faUserCheck,
  faChalkboardTeacher,
  faClipboardCheck,
  faFileAlt,
} from "@fortawesome/free-solid-svg-icons";
import { faMap } from "@fortawesome/free-solid-svg-icons";
import { Course, Lesson } from "../types";

export const cartographyCourse: Course = {
  id: "cartography",
  name: "Cartography & Map Design Course",
  description:
    "Comprehensive training in cartographic principles, data processing, map design, and relief representation techniques",
  weeks: 7,
  lessons: {
    1: {
      title: "Class 1",
      title1: "Introduction to Cartography",
      objectives: [
        "Understand fundamental cartographic principles",
        "Identify various raw data sources",
        "Recognize different types of spatial data",
        "Explain the importance of accurate data collection",
      ],
      content: [
        "History and evolution of cartography",
        "Base maps and their role in cartography",
        "Coordinate systems and applications",
        "Distance measurement techniques",
        "Aerial photography interpretation",
        "Satellite imagery analysis",
        "Bearing and direction concepts",
      ],
      practical: "Data source identification exercise",
      assessments: [
        { icon: faEye, label: "Direct observation" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    2: {
      title: "Class 2",
      title1: "Raw Data Continued & Processing Tools",
      objectives: [
        "Understand reduced levels and their significance",
        "Identify appropriate tools for data processing",
        "Recognize equipment requirements for cartography",
        "Apply basic data processing techniques",
      ],
      content: [
        "Understanding reduced levels and elevation data",
        "Digital data processing tools overview",
        "GIS software introduction",
        "Data conversion techniques",
        "Coordinate transformation basics",
        "Data accuracy assessment",
        "Equipment maintenance best practices",
      ],
      practical: "Software demonstration, data conversion exercise",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faPen, label: "Written test" },
      ],
      type: "theory",
    },
    3: {
      title: "Class 3",
      title1: "Raw Data Processing Techniques",
      objectives: [
        "Clean and organize spatial datasets",
        "Identify and correct data errors",
        "Apply data validation techniques",
        "Prepare data for cartographic use",
      ],
      content: [
        "Data cleaning methodologies",
        "Error detection and correction",
        "Data organization strategies",
        "Attribute management",
        "Quality control procedures",
        "Data standardization techniques",
      ],
      practical: "Data cleaning and organization exercise",
      assessments: [
        { icon: faComments, label: "Oral questioning" },
        { icon: faUserCheck, label: "Supervised exercise" },
      ],
      type: "practical",
    },
    4: {
      title: "Class 4",
      title1: "Georeferencing Processed Data",
      objectives: [
        "Understand georeferencing concepts",
        "Apply georeferencing techniques",
        "Transform between coordinate systems",
        "Assess georeferencing accuracy",
      ],
      content: [
        "Georeferencing fundamentals",
        "Coordinate reference systems",
        "Transformation parameters",
        "Ground control point selection",
        "Accuracy assessment methods",
        "Error propagation in georeferencing",
      ],
      practical: "Hands-on georeferencing practice with various datasets",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faUserCheck, label: "Supervised exercise" },
      ],
      type: "practical",
    },
    5: {
      title: "Class 5",
      title1: "Map and Plan Designing I",
      objectives: [
        "Design different types of maps",
        "Apply cartographic design principles",
        "Select appropriate map elements",
        "Create RIM, topographic, and atlas maps",
      ],
      content: [
        "Rural Index Map (RIM) design",
        "Topographic map characteristics",
        "Atlas map composition",
        "Map layout principles",
        "Color theory in cartography",
        "Typography for maps",
      ],
      practical: "Map design exercise focusing on different map types",
      assessments: [
        { icon: faPen, label: "Written test" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    6: {
      title: "Class 6",
      title1: "Map and Plan Designing II",
      objectives: [
        "Create specialized plan designs",
        "Design thematic maps for specific purposes",
        "Develop geological and cadastral plans",
        "Apply legal requirements to deed plans",
      ],
      content: [
        "Deed plan specifications",
        "Thematic map design techniques",
        "Geological map symbology",
        "Cadastral plan requirements",
        "Land parcel representation",
        "Legal aspects of map design",
      ],
      practical: "Specialized map design project",
      assessments: [
        { icon: faEye, label: "Direct observation" },
        { icon: faFileAlt, label: "Assignment" },
      ],
      type: "practical",
    },
    7: {
      title: "Class 7",
      title1: "Understanding Map Scale",
      objectives: [
        "Differentiate between map scales",
        "Select appropriate scales for different purposes",
        "Understand scale-dependent generalization",
        "Apply scale concepts to map design",
      ],
      content: [
        "Large scale vs. small scale maps",
        "Medium scale applications",
        "Scale-dependent feature representation",
        "Generalization techniques",
        "Scale accuracy considerations",
        "Choosing appropriate scales",
      ],
      practical: "Scale selection exercise for various mapping scenarios",
      assessments: [
        { icon: faPen, label: "Written test" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    8: {
      title: "Class 8",
      title1: "Scale Representation Techniques",
      objectives: [
        "Apply different scale representation methods",
        "Create graphical scales",
        "Calculate representative fractions",
        "Use statement scales appropriately",
      ],
      content: [
        "Graphical scale design",
        "Representative fraction calculations",
        "Statement scale applications",
        "Scale conversions",
        "Scale accuracy verification",
        "Digital scale representation",
      ],
      practical: "Scale representation exercises and conversions",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faUserCheck, label: "Supervised exercise" },
      ],
      type: "practical",
    },
    9: {
      title: "Class 9",
      title1: "Map Production Techniques",
      objectives: [
        "Apply cartographic design principles",
        "Create effective map symbology",
        "Implement proper labeling techniques",
        "Design comprehensive map legends",
      ],
      content: [
        "Map layout composition",
        "Symbol design and selection",
        "Label placement strategies",
        "Legend design principles",
        "Color application in maps",
        "Visual hierarchy in cartography",
      ],
      practical: "Complete map production project",
      assessments: [
        { icon: faEye, label: "Observation" },
        { icon: faClipboardCheck, label: "Practical test" },
      ],
      type: "practical",
    },
    10: {
      title: "Class 10",
      title1: "Map Projection Principles",
      objectives: [
        "Understand map projection fundamentals",
        "Identify projection needs for geographic areas",
        "Select appropriate projections",
        "Recognize projection distortions",
      ],
      content: [
        "Map projection concepts",
        "Projection selection criteria",
        "Geographic area considerations",
        "Distortion types and patterns",
        "Projection properties",
        "Case studies of projection applications",
      ],
      practical: "Projection selection exercise for different regions",
      assessments: [
        { icon: faComments, label: "Oral questioning" },
        { icon: faPen, label: "Written test" },
      ],
      type: "theory",
    },
    11: {
      title: "Class 11",
      title1: "Map Projection Types",
      objectives: [
        "Identify different projection types",
        "Understand Mercator projection characteristics",
        "Apply World Geodetic System (WGS)",
        "Recognize projection limitations",
      ],
      content: [
        "Mercator projection properties",
        "World Geodetic System (WGS) standards",
        "Conic projections",
        "Azimuthal projections",
        "Projection limitations",
        "Appropriate use cases",
      ],
      practical: "Projection analysis and comparison",
      assessments: [
        { icon: faEye, label: "Direct observation" },
        { icon: faUserCheck, label: "Supervised exercise" },
      ],
      type: "theory",
    },
    12: {
      title: "Class 12",
      title1: "Applying Map Projections",
      objectives: [
        "Perform projection transformations",
        "Reproject spatial datasets",
        "Assess transformation accuracy",
        "Apply projections in GIS software",
      ],
      content: [
        "Projection transformation methods",
        "Coordinate conversion techniques",
        "Reprojection workflows",
        "Accuracy assessment",
        "GIS software tools for projection",
        "Common transformation errors",
      ],
      practical: "Hands-on projection transformation exercises",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "practical",
    },
    13: {
      title: "Class 13",
      title1: "Relief Representation Fundamentals",
      objectives: [
        "Process raw elevation data",
        "Apply georeferencing to elevation data",
        "Use tools for relief processing",
        "Prepare data for relief representation",
      ],
      content: [
        "Elevation data sources",
        "Digital Elevation Models (DEMs)",
        "Georeferencing elevation data",
        "Data interpolation techniques",
        "Slope and aspect calculations",
        "Data preparation workflows",
      ],
      practical: "Elevation data processing exercise",
      assessments: [
        { icon: faComments, label: "Oral questioning" },
        { icon: faFileAlt, label: "Assignment" },
      ],
      type: "theory",
    },
    14: {
      title: "Class 14",
      title1: "Methods of Relief Representation",
      objectives: [
        "Apply various relief representation techniques",
        "Create contour maps",
        "Implement hill shading",
        "Design layered tint representations",
        "Produce digital terrain models",
      ],
      content: [
        "Contouring techniques",
        "Hill shading principles",
        "Layer tinting applications",
        "Hachuring methods",
        "Rock drawing techniques",
        "Digital Terrain Models (DTMs)",
        "Spot height placement",
        "Relief map design",
      ],
      practical: "Comprehensive relief representation project",
      assessments: [
        { icon: faClipboardCheck, label: "Practical test" },
        { icon: faEye, label: "Observation" },
        { icon: faPen, label: "Written test" },
      ],
      type: "assessment",
    },
  },
  stats: {
    classes: 14,
    weeks: 7,
    categories: 8,
    exercises: "14+",
  },
  gradient: "linear-gradient(135deg, #e74c3c, #922b21)",
  icon: faMap,
  modules: 10,
  hours: 20,
  category: "Field Techniques",
};
