import {
  faClipboardCheck,
  faComments,
  faPen,
  faUserCheck,
  faEye,
  faFileAlt,
  faChalkboardTeacher,
  faMapMarkerAlt,
} from "@fortawesome/free-solid-svg-icons";
import { Course, Lesson } from "../types";

export const controlSurveyCourse: Course = {
  id: "control-survey",
  name: "Control Survey Course",
  description:
    "Comprehensive training in control survey techniques and monumentation",
  weeks: 7,
  lessons: {
    1: {
      title: "Class 1",
      title1: "Reconnaissance Tools and Equipment",
      objectives: [
        "Identify essential reconnaissance tools",
        "Prepare equipment for survey reconnaissance",
        "Apply tools to field scenarios",
        "Demonstrate proper handling of survey equipment",
      ],
      content: [
        "Field documentation: notebooks and pens",
        "Calculation tools: calculators",
        "Scale rules and map interpretation",
        "Equipment maintenance procedures",
        "Field safety protocols",
      ],
      practical: "Equipment preparation demonstration",
      assessments: [
        { icon: faEye, label: "Direct observation" },
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    2: {
      title: "Class 2",
      title1: "Site Characteristics Analysis",
      objectives: [
        "Analyze site topography",
        "Evaluate terrain challenges",
        "Identify optimal control point locations",
        "Document site conditions",
      ],
      content: [
        "Topographical feature assessment",
        "Terrain analysis techniques",
        "Accessibility evaluation",
        "Obstacle identification",
        "Preliminary network planning",
      ],
      practical: "Field site assessment exercise",
      assessments: [
        { icon: faPen, label: "Written tests" },
        { icon: faUserCheck, label: "Practicals" },
      ],
      type: "practical",
    },
    3: {
      title: "Class 3",
      title1: "Reconnaissance Reporting",
      objectives: [
        "Compile reconnaissance findings",
        "Structure survey reports",
        "Analyze site suitability",
        "Propose control network design",
      ],
      content: [
        "Report format and standards",
        "Data synthesis techniques",
        "Network design principles",
        "Risk assessment documentation",
        "Recommendations formulation",
      ],
      practical: "Report drafting exercise",
      assessments: [
        { icon: faPen, label: "Written tests" },
        { icon: faUserCheck, label: "Practicals" },
      ],
      type: "theory",
    },
    4: {
      title: "Class 4",
      title1: "Monumentation Tools",
      objectives: [
        "Identify monumentation tools",
        "Operate basic establishment equipment",
        "Apply safety protocols",
        "Select appropriate marking materials",
      ],
      content: [
        "Hammer and peg applications",
        "Spade and shovel techniques",
        "Temporary vs permanent marking",
        "Material selection criteria",
        "Equipment maintenance",
      ],
      practical: "Tool handling demonstration",
      assessments: [
        { icon: faEye, label: "Direct observation" },
        { icon: faChalkboardTeacher, label: "Demonstration" },
      ],
      type: "practical",
    },
    5: {
      title: "Class 5",
      title1: "Survey Instrumentation",
      objectives: [
        "Operate total stations and GNSS",
        "Set up ranging rods and tapes",
        "Perform instrument calibration",
        "Apply measurement techniques",
      ],
      content: [
        "Total station components",
        "GNSS receiver operation",
        "Tape measurement procedures",
        "Ranging rod applications",
        "Instrument error checks",
      ],
      practical: "Instrument setup demonstration",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    6: {
      title: "Class 6",
      title1: "Advanced Survey Equipment",
      objectives: [
        "Operate theodolites effectively",
        "Prepare permanent monuments",
        "Mix and apply monument materials",
        "Implement quality control",
      ],
      content: [
        "Theodolite setup and operation",
        "Sand-cement mixing ratios",
        "Iron pin installation",
        "Monument durability factors",
        "Quality assurance protocols",
      ],
      practical: "Material preparation exercise",
      assessments: [
        { icon: faPen, label: "Written tests" },
        { icon: faUserCheck, label: "Practicals" },
      ],
      type: "practical",
    },
    7: {
      title: "Class 7",
      title1: "Control Survey Methods",
      objectives: [
        "Execute traverse surveys",
        "Apply GNSS positioning techniques",
        "Perform precise taping",
        "Select appropriate survey methods",
      ],
      content: [
        "Traverse survey procedures",
        "Static GNSS surveying",
        "Taping methods and corrections",
        "Method selection criteria",
        "Accuracy standards",
      ],
      practical: "Method comparison demonstration",
      assessments: [
        { icon: faEye, label: "Direct observation" },
        { icon: faChalkboardTeacher, label: "Demonstration" },
      ],
      type: "theory",
    },
    8: {
      title: "Class 8",
      title1: "Field Data Collection",
      objectives: [
        "Collect control survey data",
        "Apply appropriate field techniques",
        "Maintain field notes",
        "Implement quality checks",
      ],
      content: [
        "Field measurement procedures",
        "Data recording standards",
        "Error detection techniques",
        "Instrument handling in field conditions",
        "Team coordination methods",
      ],
      practical: "Field data collection session",
      assessments: [
        { icon: faUserCheck, label: "Practicals" },
        { icon: faPen, label: "Written tests" },
      ],
      type: "practical",
    },
    9: {
      title: "Class 9",
      title1: "Data Computation",
      objectives: [
        "Reduce field observations",
        "Perform coordinate calculations",
        "Apply statistical analysis",
        "Verify data accuracy",
      ],
      content: [
        "Data reduction techniques",
        "Coordinate computation methods",
        "Error propagation analysis",
        "Statistical checks",
        "Network adjustment fundamentals",
      ],
      practical: "Computation exercises",
      assessments: [
        { icon: faEye, label: "Direct observation" },
        { icon: faPen, label: "Written tests" },
      ],
      type: "theory",
    },
    10: {
      title: "Class 10",
      title1: "Monumentation Types",
      objectives: [
        "Identify monumentation types",
        "Select appropriate monuments",
        "Prepare IPC and IPCU monuments",
        "Apply installation standards",
      ],
      content: [
        "Iron-pin concrete (IPC) monuments",
        "Iron-pin concrete under (IPCU) markers",
        "Site-specific monument selection",
        "Durability considerations",
        "Installation best practices",
      ],
      practical: "Monument preparation demonstration",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "practical",
    },
    11: {
      title: "Class 11",
      title1: "Monument Placement",
      objectives: [
        "Position monuments accurately",
        "Install pipe-in-concrete markers",
        "Verify placement quality",
        "Document monument locations",
      ],
      content: [
        "Placement surveying techniques",
        "Pipe-in-concrete installation",
        "Position verification methods",
        "As-built documentation",
        "Quality control checks",
      ],
      practical: "Field placement exercise",
      assessments: [
        { icon: faUserCheck, label: "Practicals" },
        { icon: faPen, label: "Written tests" },
      ],
      type: "practical",
    },
    12: {
      title: "Class 12",
      title1: "Monument Construction",
      objectives: [
        "Construct durable monuments",
        "Apply material mixing techniques",
        "Ensure long-term stability",
        "Implement construction standards",
      ],
      content: [
        "Concrete mixing procedures",
        "Reinforcement techniques",
        "Curing and protection methods",
        "Construction tolerances",
        "Durability enhancement",
      ],
      practical: "Monument construction exercise",
      assessments: [
        { icon: faUserCheck, label: "Practicals" },
        { icon: faChalkboardTeacher, label: "Demonstration" },
      ],
      type: "practical",
    },
    13: {
      title: "Class 13",
      title1: "Integrated Review",
      objectives: [
        "Synthesize reconnaissance principles",
        "Evaluate data collection techniques",
        "Assess monumentation methods",
        "Develop problem-solving strategies",
      ],
      content: [
        "Reconnaissance best practices",
        "Data collection challenges",
        "Monumentation quality factors",
        "Integrated workflow analysis",
        "Case study review",
      ],
      practical: "Group problem-solving session",
      assessments: [
        { icon: faEye, label: "Direct observation" },
        { icon: faComments, label: "Q&A session" },
      ],
      type: "theory",
    },
    14: {
      title: "Class 14",
      title1: "Final Assessment",
      objectives: [
        "Demonstrate field reconnaissance",
        "Collect control survey data",
        "Install permanent monuments",
        "Verify positional accuracy",
      ],
      content: [
        "Comprehensive field exercise",
        "Data collection assessment",
        "Monumentation practical test",
        "Accuracy verification techniques",
        "Quality assurance protocols",
      ],
      practical: "Full field assessment",
      assessments: [
        { icon: faUserCheck, label: "Practicals" },
        { icon: faPen, label: "Written test" },
      ],
      type: "assessment",
    },
  },
  stats: {
    classes: 14,
    weeks: 7,
    categories: 4,
    exercises: "14+",
  },
  gradient: "linear-gradient(135deg, #e74c3c, #c0392b)",
  icon: faMapMarkerAlt,
  modules: 7,
  hours: 28,
  category: "Control Survey",
};
