import {
  faClipboardCheck,
  faComments,
  faPen,
  faUserCheck,
  faEye,
  faFileAlt,
  faChalkboardTeacher,
  faRuler,
} from "@fortawesome/free-solid-svg-icons";
import { Course, Lesson } from "../types";

export const engineeringSurveyCourse: Course = {
  id: "engineering-survey-1",
  name: "Engineering Survey Course",
  description:
    "Comprehensive training in engineering survey techniques and construction setting out",
  weeks: 7,
  lessons: {
    1: {
      title: "Class 1",
      title1: "Reconnaissance Tools and Equipment",
      objectives: [
        "Identify engineering survey reconnaissance tools",
        "Explain applications of survey equipment",
        "Select appropriate tools for site investigation",
        "Apply safety procedures for field equipment",
      ],
      content: [
        "Field documentation tools: notebooks, pens",
        "Measurement instruments: tapes, scale rules",
        "Map interpretation techniques",
        "Calculator applications in survey planning",
        "Equipment maintenance and handling",
      ],
      practical: "Equipment identification exercise",
      assessments: [
        { icon: faEye, label: "Direct observation" },
        { icon: faComments, label: "Oral questioning" },
        { icon: faPen, label: "Written test" },
      ],
      type: "theory",
    },
    2: {
      title: "Class 2",
      title1: "Site Analysis and Reporting",
      objectives: [
        "Analyze terrain and contour characteristics",
        "Assess site accessibility and challenges",
        "Document site features and conditions",
        "Prepare reconnaissance reports",
      ],
      content: [
        "Topographical feature identification",
        "Terrain assessment methodologies",
        "Contour interpretation",
        "Report structure and standards",
        "Risk assessment documentation",
      ],
      practical: "Field reconnaissance exercise",
      assessments: [
        { icon: faUserCheck, label: "Practical exercise" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "practical",
    },
    3: {
      title: "Class 3",
      title1: "Ground Level Measurement Instruments",
      objectives: [
        "Identify leveling instruments and accessories",
        "Set up tripods and leveling equipment",
        "Operate leveling instruments safely",
        "Maintain field equipment",
      ],
      content: [
        "Level types and components",
        "Tripod setup techniques",
        "Levelling staff applications",
        "Ranging rod usage",
        "Field booking documentation",
      ],
      practical: "Instrument setup demonstration",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faUserCheck, label: "Practical setup" },
        { icon: faPen, label: "Written test" },
      ],
      type: "theory",
    },
    4: {
      title: "Class 4",
      title1: "Control Point Identification and Marking",
      objectives: [
        "Locate existing control points",
        "Mark new control positions",
        "Use marking tools effectively",
        "Apply monumentation techniques",
      ],
      content: [
        "Control point identification methods",
        "Pegging and marking procedures",
        "Mallet and panga applications",
        "Safety in marking operations",
        "Documentation of control points",
      ],
      practical: "Field marking exercise",
      assessments: [
        { icon: faEye, label: "Direct observation" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "practical",
    },
    5: {
      title: "Class 5",
      title1: "Field Level Measurement",
      objectives: [
        "Perform accurate ground level measurements",
        "Conduct differential leveling",
        "Apply correct instrument handling",
        "Ensure measurement accuracy",
      ],
      content: [
        "Leveling instrument operation",
        "Staff reading techniques",
        "Instrument calibration checks",
        "Error minimization strategies",
        "Field measurement procedures",
      ],
      practical: "Field leveling exercise",
      assessments: [
        { icon: faUserCheck, label: "Practical exercise" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "practical",
    },
    6: {
      title: "Class 6",
      title1: "Level Data Recording",
      objectives: [
        "Record measurements in level books",
        "Apply standard booking conventions",
        "Perform arithmetic checks",
        "Maintain data integrity",
      ],
      content: [
        "Levelling book formats",
        "Data entry standards",
        "Field note organization",
        "Reduction techniques",
        "Error detection methods",
      ],
      practical: "Data recording session",
      assessments: [
        { icon: faPen, label: "Written test" },
        { icon: faUserCheck, label: "Supervised practical" },
      ],
      type: "practical",
    },
    7: {
      title: "Class 7",
      title1: "Profile Drafting Tools",
      objectives: [
        "Select appropriate drafting tools",
        "Prepare materials for profile drawing",
        "Apply CAD software for drafting",
        "Implement manual drafting techniques",
      ],
      content: [
        "AutoCAD for profile drafting",
        "Manual drafting tools: scales, pens",
        "Tracing and blueprint techniques",
        "Graph paper applications",
        "Straight edge and protractor use",
      ],
      practical: "Drafting tools demonstration",
      assessments: [
        { icon: faEye, label: "Direct observation" },
        { icon: faChalkboardTeacher, label: "Demonstration" },
      ],
      type: "theory",
    },
    8: {
      title: "Class 8",
      title1: "Level Reduction Techniques",
      objectives: [
        "Reduce field levels accurately",
        "Apply rise and fall method",
        "Perform arithmetic checks",
        "Calculate height differences",
      ],
      content: [
        "Arithmetical checking procedures",
        "Rise and fall calculations",
        "Height of collimation method",
        "Error distribution techniques",
        "Reduction workflow documentation",
      ],
      practical: "Level reduction calculations",
      assessments: [
        { icon: faPen, label: "Written test" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    9: {
      title: "Class 9",
      title1: "Profile Plotting",
      objectives: [
        "Plot longitudinal sections",
        "Draw cross sections",
        "Apply correct scaling techniques",
        "Annotate profiles accurately",
      ],
      content: [
        "Vertical exaggeration principles",
        "Scale selection criteria",
        "Plotting standards and conventions",
        "Annotation and labeling",
        "Digital vs manual plotting",
      ],
      practical: "Profile drawing exercise",
      assessments: [
        { icon: faUserCheck, label: "Practical exercise" },
        { icon: faEye, label: "Observation" },
      ],
      type: "practical",
    },
    10: {
      title: "Class 10",
      title1: "Setting Out Instruments",
      objectives: [
        "Identify setting out equipment",
        "Prepare instruments for field use",
        "Operate total stations and GNSS",
        "Maintain setting out tools",
      ],
      content: [
        "Total station setup and operation",
        "GNSS receiver applications",
        "Leveling instruments for setting out",
        "Pegging and marking tools",
        "Accessory equipment handling",
      ],
      practical: "Instrument setup demonstration",
      assessments: [
        { icon: faEye, label: "Direct observation" },
        { icon: faChalkboardTeacher, label: "Demonstration" },
      ],
      type: "theory",
    },
    11: {
      title: "Class 11",
      title1: "Setting Out Fundamentals",
      objectives: [
        "Conduct site safety assessments",
        "Identify control points for setting out",
        "Explain purpose of setting out",
        "Apply quality control measures",
      ],
      content: [
        "Site safety protocols",
        "Control network verification",
        "Setting out objectives",
        "Accuracy requirements",
        "Documentation standards",
      ],
      practical: "Safety assessment exercise",
      assessments: [
        { icon: faPen, label: "Written test" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    12: {
      title: "Class 12",
      title1: "Setting Out Methods",
      objectives: [
        "Apply coordinate setting out",
        "Perform theodolite and level methods",
        "Execute offset techniques",
        "Verify setting out accuracy",
      ],
      content: [
        "Coordinate calculation methods",
        "Theodolite angle measurement",
        "Offset measurement techniques",
        "Leveling for height control",
        "Field verification procedures",
      ],
      practical: "Setting out field exercise",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faClipboardCheck, label: "Practical assessment" },
      ],
      type: "practical",
    },
    13: {
      title: "Class 13",
      title1: "Curve Setting Out",
      objectives: [
        "Set out vertical curves",
        "Establish horizontal curves",
        "Calculate curve parameters",
        "Apply specialized setting out techniques",
      ],
      content: [
        "Vertical curve calculations",
        "Horizontal curve geometry",
        "Chord and offset methods",
        "Transition curve principles",
        "Instrumentation for curve setting",
      ],
      practical: "Curve setting out exercise",
      assessments: [
        { icon: faClipboardCheck, label: "Practical test" },
        { icon: faEye, label: "Observation" },
      ],
      type: "practical",
    },
    14: {
      title: "Class 14",
      title1: "Setting Out Applications",
      objectives: [
        "Set out building foundations",
        "Establish trench alignments",
        "Place slope stakes",
        "Verify construction positioning",
      ],
      content: [
        "Building corner marking",
        "Trench alignment techniques",
        "Slope stake placement",
        "As-built verification",
        "Construction tolerances",
      ],
      practical: "Full setting out project",
      assessments: [
        { icon: faClipboardCheck, label: "Practical assessment" },
        { icon: faComments, label: "Oral questioning" },
        { icon: faPen, label: "Written test" },
      ],
      type: "assessment",
    },
  },
  stats: {
    classes: 14,
    weeks: 7,
    categories: 5,
    exercises: "14+",
  },
  gradient: "linear-gradient(135deg, #9b59b6, #8e44ad)",
  icon: faRuler,
  modules: 14,
  hours: 28,
  category: "Engineering Survey",
};
