import {
  faClipboardCheck,
  faComments,
  faPen,
  faUserCheck,
  faEye,
  faFileAlt,
  faChalkboardTeacher,
  faServer,
  faDatabase,
} from "@fortawesome/free-solid-svg-icons";
import { Course, Lesson } from "../types";

export const gisCourse: Course = {
  id: "gis",
  name: "GIS Data Management Course",
  description:
    "Comprehensive training in GIS data collection, processing, and archival techniques",
  weeks: 7,
  lessons: {
    1: {
      title: "Class 1",
      title1: "GIS Data Sources: Traditional Methods",
      objectives: [
        "Identify traditional GIS data sources",
        "Evaluate existing map resources",
        "Apply ground survey techniques for GIS",
        "Assess source data quality",
      ],
      content: [
        "Existing map interpretation",
        "Ground survey methodologies",
        "Source reliability assessment",
        "Metadata standards for traditional sources",
        "Data acquisition protocols",
      ],
      practical: "Map source evaluation exercise",
      assessments: [
        { icon: faPen, label: "Written tests" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    2: {
      title: "Class 2",
      title1: "GIS Data Sources: Digital Technologies",
      objectives: [
        "Utilize remote sensing data",
        "Apply photogrammetry techniques",
        "Access digital data repositories",
        "Analyze statistical reports for GIS",
      ],
      content: [
        "Remote sensing data acquisition",
        "Aerial photogrammetry principles",
        "Digital data banks and APIs",
        "Statistical data integration",
        "Journal research methodologies",
      ],
      practical: "Data source portfolio development",
      assessments: [
        { icon: faFileAlt, label: "Portfolio of evidence" },
        { icon: faFileAlt, label: "Project" },
      ],
      type: "practical",
    },
    3: {
      title: "Class 3",
      title1: "GIS Data Collection Methods",
      objectives: [
        "Compare data collection methodologies",
        "Select appropriate collection techniques",
        "Implement field data collection",
        "Ensure data quality standards",
      ],
      content: [
        "Field surveying for GIS",
        "Mobile data collection apps",
        "Aerial data capture techniques",
        "Crowdsourcing approaches",
        "Quality control protocols",
      ],
      practical: "Field data collection exercise",
      assessments: [
        { icon: faUserCheck, label: "Practical" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "practical",
    },
    4: {
      title: "Class 4",
      title1: "Digital Storage Infrastructure",
      objectives: [
        "Configure server storage solutions",
        "Manage external storage devices",
        "Implement data backup strategies",
        "Ensure storage security",
      ],
      content: [
        "Server architecture for GIS",
        "RAID configurations",
        "External drive management",
        "Cloud storage options",
        "Data security protocols",
      ],
      practical: "Storage system configuration",
      assessments: [
        { icon: faPen, label: "Written tests" },
        { icon: faChalkboardTeacher, label: "Demonstration" },
      ],
      type: "theory",
    },
    5: {
      title: "Class 5",
      title1: "Physical Storage Systems",
      objectives: [
        "Organize physical data storage",
        "Implement cataloging systems",
        "Maintain filing systems",
        "Develop retrieval protocols",
      ],
      content: [
        "Filing cabinet organization",
        "Map cataloging standards",
        "Physical media storage",
        "Retrieval workflow design",
        "Preservation techniques",
      ],
      practical: "Physical storage organization",
      assessments: [
        { icon: faUserCheck, label: "Practical" },
        { icon: faClipboardCheck, label: "Third party report" },
      ],
      type: "practical",
    },
    6: {
      title: "Class 6",
      title1: "GIS Data Recording Standards",
      objectives: [
        "Apply data recording protocols",
        "Implement metadata standards",
        "Ensure data integrity",
        "Develop documentation workflows",
      ],
      content: [
        "Data dictionary creation",
        "Metadata standards (ISO 19115)",
        "Attribute recording protocols",
        "Temporal data management",
        "Quality assurance documentation",
      ],
      practical: "Metadata documentation project",
      assessments: [
        { icon: faFileAlt, label: "Portfolio of evidence" },
        { icon: faFileAlt, label: "Project" },
      ],
      type: "practical",
    },
    7: {
      title: "Class 7",
      title1: "Data Processing Tools",
      objectives: [
        "Identify GIS processing software",
        "Compare tool functionalities",
        "Select appropriate processing tools",
        "Automate processing workflows",
      ],
      content: [
        "Desktop GIS software (ArcGIS, QGIS)",
        "Spatial analysis extensions",
        "Open-source processing tools",
        "Scripting for automation (Python)",
        "Workflow optimization techniques",
      ],
      practical: "Tool comparison analysis",
      assessments: [
        { icon: faPen, label: "Written tests" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    8: {
      title: "Class 8",
      title1: "Data Pre-processing Techniques",
      objectives: [
        "Prepare raw GIS data",
        "Implement pre-processing workflows",
        "Transform coordinate systems",
        "Verify pre-processed data quality",
      ],
      content: [
        "Data format conversion",
        "Coordinate system transformation",
        "Projection handling",
        "Data subset creation",
        "Quality validation methods",
      ],
      practical: "Data pre-processing project",
      assessments: [
        { icon: faUserCheck, label: "Practical" },
        { icon: faFileAlt, label: "Project" },
      ],
      type: "practical",
    },
    9: {
      title: "Class 9",
      title1: "Data Cleaning Methods",
      objectives: [
        "Identify data errors",
        "Apply cleaning algorithms",
        "Handle missing data",
        "Maintain data consistency",
      ],
      content: [
        "Topological error correction",
        "Attribute validation",
        "Outlier detection",
        "Data gap handling",
        "Consistency checking protocols",
      ],
      practical: "Data cleaning exercise",
      assessments: [
        { icon: faPen, label: "Written tests" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    10: {
      title: "Class 10",
      title1: "Data Formatting and Integration",
      objectives: [
        "Standardize data formats",
        "Integrate multi-source data",
        "Resolve schema conflicts",
        "Create unified datasets",
      ],
      content: [
        "Format standardization techniques",
        "Schema mapping methods",
        "Data conflation approaches",
        "Temporal integration",
        "Multi-scale data handling",
      ],
      practical: "Data integration project",
      assessments: [
        { icon: faUserCheck, label: "Practical" },
        { icon: faFileAlt, label: "Portfolio of evidence" },
      ],
      type: "practical",
    },
    11: {
      title: "Class 11",
      title1: "Processed Data Presentation",
      objectives: [
        "Visualize processed data",
        "Design effective map products",
        "Generate analytical reports",
        "Create interactive dashboards",
      ],
      content: [
        "Cartographic design principles",
        "Thematic mapping techniques",
        "Statistical visualization",
        "Web mapping applications",
        "Dashboard development",
      ],
      practical: "Data presentation project",
      assessments: [
        { icon: faFileAlt, label: "Project" },
        { icon: faClipboardCheck, label: "Third party report" },
      ],
      type: "practical",
    },
    12: {
      title: "Class 12",
      title1: "Data Cataloging Systems",
      objectives: [
        "Implement metadata catalogs",
        "Configure catalog servers",
        "Apply discovery standards",
        "Ensure catalog interoperability",
      ],
      content: [
        "Metadata catalog design",
        "CSW (Catalog Service for Web)",
        "Geonetwork implementation",
        "ISO metadata profiles",
        "Interoperability standards",
      ],
      practical: "Catalog system setup",
      assessments: [
        { icon: faUserCheck, label: "Practical" },
        { icon: faPen, label: "Written tests" },
      ],
      type: "practical",
    },
    13: {
      title: "Class 13",
      title1: "Data Categorization Methods",
      objectives: [
        "Develop classification schemes",
        "Apply thematic categorization",
        "Implement hierarchical structures",
        "Ensure consistent taxonomy",
      ],
      content: [
        "Classification system design",
        "Thematic category definition",
        "Hierarchical organization",
        "Taxonomy development",
        "Cross-walking classifications",
      ],
      practical: "Data categorization exercise",
      assessments: [
        { icon: faComments, label: "Oral questioning" },
        { icon: faFileAlt, label: "Portfolio of evidence" },
      ],
      type: "theory",
    },
    14: {
      title: "Class 14",
      title1: "Final Project and Archival",
      objectives: [
        "Implement cadastral map storage",
        "Present comprehensive GIS project",
        "Apply all course outcomes",
        "Ensure long-term data preservation",
      ],
      content: [
        "Cadastral data storage systems",
        "Long-term preservation strategies",
        "Final project integration",
        "Presentation techniques",
        "Archival quality assurance",
      ],
      practical: "Comprehensive GIS project",
      assessments: [
        { icon: faFileAlt, label: "Project" },
        { icon: faFileAlt, label: "Portfolio of evidence" },
        { icon: faClipboardCheck, label: "Third party report" },
      ],
      type: "assessment",
    },
  },
  stats: {
    classes: 14,
    weeks: 7,
    categories: 4,
    exercises: "14+",
  },
  gradient: "linear-gradient(135deg, #1abc9c, #16a085)",
  icon: faDatabase,
  modules: 7,
  hours: 28,
  category: "GIS Data Management",
};
