import {
  faClipboardCheck,
  faComments,
  faPen,
  faUserCheck,
  faEye,
  faFileAlt,
  faChalkboardTeacher,
  faBalanceScale,
} from "@fortawesome/free-solid-svg-icons";
import { Course, Lesson } from "../types";

export const landLawCourse: Course = {
  id: "land-law-1",
  name: "Land Laws and Ownership Course",
  description:
    "Comprehensive training in land legislation, ownership verification, and transaction compliance",
  weeks: 7,
  lessons: {
    1: {
      title: "Class 1",
      title1: "Constitutional Foundations of Land Law",
      objectives: [
        "Identify constitutional sources of land law",
        "Explain the hierarchy of land legislation",
        "Analyze constitutional provisions on land rights",
        "Recognize fundamental land rights principles",
      ],
      content: [
        "Constitutional framework for land governance",
        "Hierarchy of legal instruments",
        "Land rights in the Bill of Rights",
        "Constitutional land reform provisions",
        "Jurisdictional distribution of land authority",
      ],
      practical: "Constitutional clause analysis exercise",
      assessments: [{ icon: faEye, label: "Direct observation" }],
      type: "theory",
    },
    2: {
      title: "Class 2",
      title1: "Contemporary Land Legislation",
      objectives: [
        "Identify current land statutes",
        "Analyze key provisions of land acts",
        "Differentiate between land law categories",
        "Apply statutory interpretation techniques",
      ],
      content: [
        "Principal land legislation review",
        "Land administration statutes",
        "Land use planning regulations",
        "Tenure security legislation",
        "Statutory interpretation methods",
      ],
      practical: "Statute mapping exercise",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faComments, label: "Oral questioning" },
        { icon: faPen, label: "Written tests" },
      ],
      type: "theory",
    },
    3: {
      title: "Class 3",
      title1: "Environmental Land Regulations",
      objectives: [
        "Identify environmental land regulations",
        "Analyze land-environment regulatory interfaces",
        "Apply sustainability principles to land use",
        "Recognize compliance requirements",
      ],
      content: [
        "Environmental impact assessment regulations",
        "Protected area restrictions",
        "Sustainable land use provisions",
        "Conservation easements",
        "Compliance monitoring frameworks",
      ],
      practical: "Regulatory compliance scenario analysis",
      assessments: [
        { icon: faPen, label: "Written tests" },
        { icon: faEye, label: "Direct observation" },
      ],
      type: "theory",
    },
    4: {
      title: "Class 4",
      title1: "Land Ownership Typologies",
      objectives: [
        "Differentiate ownership types",
        "Analyze characteristics of tenure systems",
        "Apply ownership verification frameworks",
        "Recognize legal implications of ownership forms",
      ],
      content: [
        "Freehold vs leasehold distinctions",
        "Communal tenure systems",
        "Customary land rights",
        "Public vs private ownership",
        "Verification methodology frameworks",
      ],
      practical: "Ownership type classification exercise",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    5: {
      title: "Class 5",
      title1: "Land Tenure Systems",
      objectives: [
        "Compare tenure systems globally",
        "Analyze tenure security implications",
        "Evaluate formal vs informal systems",
        "Apply tenure rights protection strategies",
      ],
      content: [
        "Formal registered tenure systems",
        "Customary tenure arrangements",
        "Informal settlement rights",
        "Tenure security indicators",
        "Conflict prevention mechanisms",
      ],
      practical: "Tenure system comparison matrix",
      assessments: [{ icon: faPen, label: "Written tests" }],
      type: "theory",
    },
    6: {
      title: "Class 6",
      title1: "Land Registration Frameworks",
      objectives: [
        "Explain land registration procedures",
        "Analyze registration system components",
        "Apply registration compliance standards",
        "Verify registration documentation",
      ],
      content: [
        "Title registration processes",
        "Cadastral system fundamentals",
        "Deeds registration vs title registration",
        "Compliance verification protocols",
        "Document authentication techniques",
      ],
      practical: "Registration document analysis",
      assessments: [{ icon: faEye, label: "Direct observation" }],
      type: "theory",
    },
    7: {
      title: "Class 7",
      title1: "Land Registration Documentation",
      objectives: [
        "Identify key registration documents",
        "Analyze document legal requirements",
        "Verify document authenticity",
        "Recognize fraudulent documentation",
      ],
      content: [
        "Title deeds components",
        "Transfer instruments",
        "Mortgage documentation",
        "Lease agreements",
        "Fraud detection techniques",
      ],
      practical: "Document verification exercise",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "practical",
    },
    8: {
      title: "Class 8",
      title1: "Ownership Verification Processes",
      objectives: [
        "Implement verification methodologies",
        "Conduct chain of title analysis",
        "Resolve ownership discrepancies",
        "Prepare verification reports",
      ],
      content: [
        "Title search procedures",
        "Historical ownership tracing",
        "Discrepancy resolution protocols",
        "Verification report standards",
        "Legal compliance certification",
      ],
      practical: "Simulated title verification",
      assessments: [
        { icon: faPen, label: "Written tests" },
        { icon: faUserCheck, label: "Practicals" },
      ],
      type: "practical",
    },
    9: {
      title: "Class 9",
      title1: "Land Transaction Frameworks",
      objectives: [
        "Identify regulated land transactions",
        "Analyze transaction compliance requirements",
        "Differentiate transaction types",
        "Apply anti-fraud measures",
      ],
      content: [
        "Sale and purchase regulations",
        "Leasing and licensing frameworks",
        "Mortgage and security transactions",
        "Compliance checklist development",
        "Fraud prevention protocols",
      ],
      practical: "Transaction classification exercise",
      assessments: [{ icon: faEye, label: "Direct observation" }],
      type: "theory",
    },
    10: {
      title: "Class 10",
      title1: "Transaction Documentation",
      objectives: [
        "Prepare essential transaction documents",
        "Analyze contractual requirements",
        "Verify document completeness",
        "Apply execution formalities",
      ],
      content: [
        "Sale agreements components",
        "Conveyancing documentation",
        "Due diligence requirements",
        "Execution formalities",
        "Witnessing and notarization",
      ],
      practical: "Document drafting exercise",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstration" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "practical",
    },
    11: {
      title: "Class 11",
      title1: "Land Records Management",
      objectives: [
        "Manage land information systems",
        "Analyze record preservation requirements",
        "Apply data privacy regulations",
        "Verify record accuracy",
      ],
      content: [
        "Registry operations and management",
        "Digital record preservation",
        "Data privacy compliance",
        "Record verification techniques",
        "Archival standards",
      ],
      practical: "Record management simulation",
      assessments: [{ icon: faPen, label: "Written tests" }],
      type: "theory",
    },
    12: {
      title: "Class 12",
      title1: "Land Dispute Case Studies",
      objectives: [
        "Analyze common land conflict scenarios",
        "Apply dispute resolution frameworks",
        "Evaluate legal arguments",
        "Develop resolution strategies",
      ],
      content: [
        "Boundary dispute analysis",
        "Ownership conflict resolution",
        "Succession and inheritance cases",
        "Adverse possession claims",
        "Alternative dispute resolution",
      ],
      practical: "Case study role-playing",
      assessments: [
        { icon: faChalkboardTeacher, label: "Demonstrations" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "practical",
    },
    13: {
      title: "Class 13",
      title1: "Land Agreement Drafting",
      objectives: [
        "Draft basic land agreements",
        "Review contractual terms",
        "Identify potential loopholes",
        "Apply standard clauses",
      ],
      content: [
        "Lease agreement drafting",
        "Sale contract essentials",
        "Easement agreements",
        "Contract review techniques",
        "Standard clause libraries",
      ],
      practical: "Agreement drafting workshop",
      assessments: [
        { icon: faUserCheck, label: "Practical exercises" },
        { icon: faComments, label: "Group discussion" },
      ],
      type: "practical",
    },
    14: {
      title: "Class 14",
      title1: "Comprehensive Assessment",
      objectives: [
        "Demonstrate land law knowledge",
        "Apply ownership verification techniques",
        "Analyze transaction compliance",
        "Resolve complex land scenarios",
      ],
      content: [
        "Integrated knowledge assessment",
        "Ownership verification simulation",
        "Transaction compliance analysis",
        "Dispute resolution scenarios",
        "Agreement drafting evaluation",
      ],
      practical: "Comprehensive mock scenarios",
      assessments: [
        { icon: faPen, label: "Written tests" },
        { icon: faFileAlt, label: "Projects" },
        { icon: faEye, label: "Direct observation" },
      ],
      type: "assessment",
    },
  },
  stats: {
    classes: 14,
    weeks: 7,
    categories: 4,
    exercises: "14+",
  },
  gradient: "linear-gradient(135deg, #34495e, #2c3e50)",
  icon: faBalanceScale,
  modules: 7,
  hours: 28,
  category: "Land Law",
};
