import {
  faClipboardCheck,
  faComments,
  faPen,
  faUserCheck,
  faEye,
  faFileAlt,
  faChalkboardTeacher,
  faTools,
} from "@fortawesome/free-solid-svg-icons";
import { Course, Lesson } from "../types";

export const surveyingCourse: Course = {
  id: "survey-instruments",
  name: "Surveying Instruments Course",
  description:
    "Comprehensive Training on Surveying Equipment and Field Techniques",
  weeks: 7,
  lessons: {
    1: {
      title: "Class 1",
      title1: "Introduction to Surveying Instruments & Safety",
      objectives: [
        "Identify different types of linear measuring instruments",
        "Understand safety protocols for surveying equipment",
        "Explain principles of EDM, optical, and sonic distance measurement",
        "Recognize proper handling techniques for surveying instruments",
      ],
      content: [
        "Introduction to surveying instruments and safety protocols",
        "Measuring tape: components and applications",
        "Electronic Distance Measurement (EDM) principles",
        "Optical distance measurement techniques",
        "Sonic distance measurement applications",
      ],
      practical: "Instrument identification exercise, safety demonstration",
      assessments: [
        { icon: faComments, label: "Oral questioning" },
        { icon: faPen, label: "Short written test" },
      ],
      type: "theory",
    },
    2: {
      title: "Class 2",
      title1: "Operations of Linear Measuring Instruments",
      objectives: [
        "Demonstrate proper use of measuring tapes",
        "Operate EDM equipment accurately",
        "Perform calibration procedures",
        "Apply maintenance best practices",
      ],
      content: [
        "Practical use of measuring tapes",
        "EDM setup and operation procedures",
        "Optical distance measurement field application",
        "Sonic measurement techniques",
        "Storage and maintenance protocols",
        "Calibration procedures and verification",
      ],
      practical: "Field measurement exercise with different instruments",
      assessments: [
        { icon: faUserCheck, label: "Supervised exercise" },
        { icon: faEye, label: "Observation" },
      ],
      type: "practical",
    },
    3: {
      title: "Class 3",
      title1: "Angle Measuring Instruments",
      objectives: [
        "Identify angle measuring instruments",
        "Explain principles of angle measurement",
        "Differentiate between total stations and compasses",
        "Understand azimuth and bearing concepts",
      ],
      content: [
        "Total station components and functions",
        "Compass types and applications",
        "Angle measurement fundamentals",
        "Horizontal and vertical angle concepts",
        "Error sources in angle measurement",
      ],
      practical: "Instrument identification and component labeling",
      assessments: [
        { icon: faFileAlt, label: "Written assignment" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    4: {
      title: "Class 4",
      title1: "Operations of Angle Measuring Instruments",
      objectives: [
        "Set up and operate total stations",
        "Measure horizontal and vertical angles",
        "Perform compass traversing",
        "Apply field adjustment techniques",
      ],
      content: [
        "Total station setup and calibration",
        "Angle measurement field procedures",
        "Bearing measurement techniques",
        "Traverse measurement methods",
        "Field adjustment and error correction",
      ],
      practical: "Field practice measuring angles and bearings",
      assessments: [{ icon: faUserCheck, label: "Supervised exercises" }],
      type: "practical",
    },
    5: {
      title: "Class 5",
      title1: "Height Measuring Instruments",
      objectives: [
        "Identify different leveling instruments",
        "Understand leveling principles",
        "Recognize components of auto/digital levels",
        "Explain differential leveling methods",
      ],
      content: [
        "Types of leveling instruments",
        "Auto level components and functions",
        "Digital level technology",
        "Differential leveling principles",
        "Benchmark establishment",
      ],
      practical: "Instrument setup and component identification",
      assessments: [{ icon: faComments, label: "Oral questioning" }],
      type: "theory",
    },
    6: {
      title: "Class 6",
      title1: "Operations of Height Measuring Instruments",
      objectives: [
        "Set up and operate auto/digital levels",
        "Perform collimation checks",
        "Adjust instrument bubbles",
        "Conduct differential leveling surveys",
      ],
      content: [
        "Leveling instrument setup procedures",
        "Collimation check techniques",
        "Bubble adjustment methods",
        "Field leveling procedures",
        "Error detection and correction",
      ],
      practical: "Differential leveling field exercise",
      assessments: [
        { icon: faClipboardCheck, label: "Practical test" },
        { icon: faUserCheck, label: "Supervised exercise" },
        { icon: faEye, label: "Observation" },
      ],
      type: "practical",
    },
    7: {
      title: "Class 7",
      title1: "Linear-Angle Measuring Instruments",
      objectives: [
        "Identify linear-angle measuring instruments",
        "Compare Total Station and GNSS technologies",
        "Understand applications of different instruments",
        "Evaluate instrument selection criteria",
      ],
      content: [
        "Total Station components and capabilities",
        "GNSS receiver types and functions",
        "Instrument comparison: accuracy, range, applications",
        "Integrated surveying systems",
        "Field application case studies",
      ],
      practical: "Instrument comparison exercise",
      assessments: [{ icon: faPen, label: "Short written test" }],
      type: "theory",
    },
    8: {
      title: "Class 8",
      title1: "Operations of Total Station",
      objectives: [
        "Set up and orient a Total Station",
        "Measure distances and angles",
        "Perform coordinate measurement",
        "Conduct topographic surveys",
      ],
      content: [
        "Total Station setup procedures",
        "Orientation and backsight techniques",
        "Distance and angle measurement",
        "Coordinate measurement methods",
        "Topographic data collection",
      ],
      practical: "Total Station field exercise",
      assessments: [{ icon: faUserCheck, label: "Supervised field exercise" }],
      type: "practical",
    },
    9: {
      title: "Class 9",
      title1: "Operations of GNSS Receivers",
      objectives: [
        "Set up GNSS equipment",
        "Collect field data",
        "Establish GNSS survey networks",
        "Perform real-time kinematic (RTK) surveys",
      ],
      content: [
        "GNSS receiver setup procedures",
        "Field data collection techniques",
        "Survey network design",
        "RTK surveying methods",
        "Data quality control",
      ],
      practical: "GNSS survey setup and data collection",
      assessments: [
        { icon: faComments, label: "Oral questioning" },
        { icon: faFileAlt, label: "Assignment" },
      ],
      type: "practical",
    },
    10: {
      title: "Class 10",
      title1: "Equipment Maintenance Procedures",
      objectives: [
        "Perform routine maintenance on Total Stations",
        "Maintain GNSS equipment",
        "Troubleshoot common issues",
        "Follow manufacturer's instructions",
      ],
      content: [
        "Total Station maintenance schedule",
        "GNSS receiver care procedures",
        "Troubleshooting common problems",
        "Battery and storage management",
        "Cleaning and calibration standards",
      ],
      practical: "Maintenance demonstration and practice",
      assessments: [
        { icon: faChalkboardTeacher, label: "Practical demonstration" },
      ],
      type: "practical",
    },
    11: {
      title: "Class 11",
      title1: "GNSS Equipment Identification",
      objectives: [
        "Identify different GNSS equipment types",
        "Understand handheld GPS applications",
        "Explain kinematic GPS principles",
        "Evaluate mapping and surveying applications",
      ],
      content: [
        "Handheld GPS devices",
        "Kinematic GPS systems",
        "Mapping applications",
        "Survey-grade GNSS equipment",
        "Data collection workflows",
      ],
      practical: "Equipment identification exercise",
      assessments: [{ icon: faPen, label: "Written test" }],
      type: "theory",
    },
    12: {
      title: "Class 12",
      title1: "GNSS Field Operations",
      objectives: [
        "Operate GNSS equipment in real-time",
        "Perform real-time field exercises",
        "Apply maintenance best practices",
        "Collect accurate field data",
      ],
      content: [
        "Real-time GNSS setup",
        "Field data collection procedures",
        "Quality control measures",
        "Maintenance during field operations",
        "Data processing workflows",
      ],
      practical: "Real-time GNSS field exercise",
      assessments: [
        { icon: faEye, label: "Observation" },
        { icon: faUserCheck, label: "Supervised fieldwork" },
      ],
      type: "practical",
    },
    13: {
      title: "Class 13",
      title1: "Instrument Review and Challenges",
      objectives: [
        "Review all instrument categories",
        "Identify common field challenges",
        "Develop problem-solving strategies",
        "Discuss best practices",
      ],
      content: [
        "Linear instrument review",
        "Angle measurement challenges",
        "Height measurement issues",
        "GNSS limitations",
        "Integrated system challenges",
      ],
      practical: "Group problem-solving session",
      assessments: [
        { icon: faComments, label: "Oral questioning" },
        { icon: faPen, label: "Revision test" },
      ],
      type: "theory",
    },
    14: {
      title: "Class 14",
      title1: "Final Practical Assessment",
      objectives: [
        "Demonstrate instrument setup proficiency",
        "Measure distances accurately",
        "Measure angles precisely",
        "Determine heights correctly",
        "Collect GNSS points",
      ],
      content: [
        "Comprehensive practical assessment",
        "Instrument setup evaluation",
        "Distance measurement accuracy",
        "Angle measurement precision",
        "Height determination techniques",
        "GNSS point collection",
      ],
      practical: "Full practical examination",
      assessments: [
        { icon: faPen, label: "Final written exam" },
        { icon: faClipboardCheck, label: "Practical test" },
      ],
      type: "assessment",
    },
  },
  stats: {
    classes: 14,
    weeks: 7,
    categories: 5,
    exercises: "14+",
  },
  gradient: "linear-gradient(135deg, #3498db, #1a5276)",
  icon: faTools,
  modules: 12,
  hours: 24,
  category: "Instrumentation",
};
