import {
  faClipboardCheck,
  faComments,
  faPen,
  faUserCheck,
  faEye,
  faFileAlt,
  faChalkboardTeacher,
  faTools,
} from "@fortawesome/free-solid-svg-icons";
import { Course, Lesson } from "../types";

export const topocourse: Course = {
  id: "topographical-survey",
  name: "Topographical Survey Course",
  description:
    "Comprehensive training in topographical survey techniques and map production",
  weeks: 7,
  lessons: {
    1: {
      title: "Class 1",
      title1: "Reconnaissance Tools and Equipment",
      objectives: [
        "Identify essential reconnaissance tools",
        "Explain the purpose of each reconnaissance tool",
        "Select appropriate equipment for survey reconnaissance",
        "Demonstrate proper handling of field equipment",
      ],
      content: [
        "Introduction to topographical survey reconnaissance",
        "Field notebooks and documentation tools",
        "Map interpretation techniques",
        "Distance measurement tools: tapes and rules",
        "Calculator applications in survey planning",
      ],
      practical: "Equipment identification and handling demonstration",
      assessments: [
        { icon: faPen, label: "Written assessment" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    2: {
      title: "Class 2",
      title1: "Site Characteristics Analysis",
      objectives: [
        "Analyze landscape features for survey planning",
        "Evaluate terrain conditions and challenges",
        "Identify natural features affecting survey design",
        "Document site conditions effectively",
      ],
      content: [
        "Topographical feature identification",
        "Terrain assessment techniques",
        "Natural feature documentation",
        "Accessibility and safety considerations",
        "Preliminary sketch preparation",
      ],
      practical: "Field site assessment exercise",
      assessments: [
        { icon: faUserCheck, label: "Practical assessment" },
        { icon: faFileAlt, label: "Project submission" },
      ],
      type: "practical",
    },
    3: {
      title: "Class 3",
      title1: "Reconnaissance Report Preparation",
      objectives: [
        "Structure a reconnaissance report",
        "Compile field observations into documentation",
        "Analyze site characteristics for survey planning",
        "Propose control point locations",
      ],
      content: [
        "Report format and standards",
        "Integration of field observations",
        "Site analysis documentation",
        "Control point planning strategies",
        "Risk assessment and mitigation planning",
      ],
      practical: "Drafting reconnaissance reports",
      assessments: [
        { icon: faPen, label: "Written test" },
        { icon: faComments, label: "Oral defense" },
      ],
      type: "theory",
    },
    4: {
      title: "Class 4",
      title1: "Control Point Establishment Tools",
      objectives: [
        "Identify control point marking tools",
        "Select appropriate monumentation materials",
        "Operate basic establishment equipment",
        "Apply safety protocols in point marking",
      ],
      content: [
        "Pegs and hammer applications",
        "Excavation tools: spades and shovels",
        "Measuring tapes for point verification",
        "Monumentation materials selection",
        "Temporary vs permanent marking techniques",
      ],
      practical: "Control point marking exercise",
      assessments: [
        { icon: faEye, label: "Observation" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "practical",
    },
    5: {
      title: "Class 5",
      title1: "Advanced Survey Instruments",
      objectives: [
        "Operate total stations and GNSS receivers",
        "Set up ranging rods and positioning equipment",
        "Prepare monumentation materials",
        "Implement instrument safety procedures",
      ],
      content: [
        "Total station components and functions",
        "GNSS receiver setup and operation",
        "Ranging rod applications",
        "Permanent monumentation techniques",
        "Equipment calibration checks",
      ],
      practical: "Instrument setup and testing",
      assessments: [{ icon: faUserCheck, label: "Practical assessment" }],
      type: "practical",
    },
    6: {
      title: "Class 6",
      title1: "Control Network Design",
      objectives: [
        "Identify existing control points",
        "Select optimal locations for new points",
        "Design control point networks",
        "Apply geometric principles in network design",
      ],
      content: [
        "Control point identification techniques",
        "Site selection criteria",
        "Network geometry planning",
        "Intervisibility assessment",
        "Accuracy requirements and specifications",
      ],
      practical: "Field control network design",
      assessments: [
        { icon: faEye, label: "Observation" },
        { icon: faPen, label: "Network design test" },
      ],
      type: "practical",
    },
    7: {
      title: "Class 7",
      title1: "Control Point Monumentation",
      objectives: [
        "Extend control networks from existing points",
        "Install permanent monuments",
        "Document control point locations",
        "Apply quality checks in monumentation",
      ],
      content: [
        "Network extension methodologies",
        "Monument installation procedures",
        "Coordinate referencing systems",
        "As-built documentation techniques",
        "Quality assurance protocols",
      ],
      practical: "Field monumentation exercise",
      assessments: [{ icon: faUserCheck, label: "Supervised exercise" }],
      type: "practical",
    },
    8: {
      title: "Class 8",
      title1: "Feature Data Collection Instruments",
      objectives: [
        "Operate total stations and GNSS for data capture",
        "Set up leveling instruments",
        "Prepare field documentation materials",
        "Select appropriate data collection tools",
      ],
      content: [
        "Total station setup and operation",
        "GNSS receiver configurations",
        "Level and tripod setup procedures",
        "Levelling staff techniques",
        "Field book documentation standards",
      ],
      practical: "Instrument setup demonstration",
      assessments: [
        { icon: faComments, label: "Oral questioning" },
        { icon: faPen, label: "Equipment test" },
      ],
      type: "theory",
    },
    9: {
      title: "Class 9",
      title1: "Data Collection Methods",
      objectives: [
        "Compare terrestrial and aerial methods",
        "Select appropriate data collection techniques",
        "Implement satellite imagery in surveys",
        "Evaluate method accuracy and limitations",
      ],
      content: [
        "Terrestrial survey procedures",
        "Aerial photogrammetry basics",
        "Satellite imagery applications",
        "Method selection criteria",
        "Accuracy assessment techniques",
      ],
      practical: "Method comparison exercise",
      assessments: [
        { icon: faClipboardCheck, label: "Practical test" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    10: {
      title: "Class 10",
      title1: "Field Data Collection Practice",
      objectives: [
        "Collect feature data using total stations",
        "Capture GNSS point data",
        "Perform leveling operations",
        "Maintain field data records",
      ],
      content: [
        "Feature coding systems",
        "Topographic point collection",
        "Height determination methods",
        "Data quality checks",
        "Field note organization",
      ],
      practical: "Field data collection session",
      assessments: [
        { icon: faEye, label: "Observation" },
        { icon: faUserCheck, label: "Supervised practical" },
      ],
      type: "practical",
    },
    11: {
      title: "Class 11",
      title1: "Digital Map Production",
      objectives: [
        "Select appropriate mapping software",
        "Prepare data for digital mapping",
        "Apply GIS principles in map creation",
        "Configure CAD environments for mapping",
      ],
      content: [
        "Software comparison: ArcGIS, QGIS, AutoCAD",
        "Data import and processing",
        "Layer management techniques",
        "Symbolization standards",
        "Coordinate system configuration",
      ],
      practical: "Software demonstration",
      assessments: [
        { icon: faPen, label: "Written test" },
        { icon: faComments, label: "Oral questioning" },
      ],
      type: "theory",
    },
    12: {
      title: "Class 12",
      title1: "Manual Drafting Techniques",
      objectives: [
        "Apply technical drawing principles",
        "Use manual drafting tools effectively",
        "Create scale-accurate maps",
        "Produce clean cartographic products",
      ],
      content: [
        "Scale rule applications",
        "Tracing paper techniques",
        "Inking and linework standards",
        "Symbol hand-rendering methods",
        "Annotation best practices",
      ],
      practical: "Manual map drafting exercise",
      assessments: [{ icon: faClipboardCheck, label: "Drawing exercise" }],
      type: "practical",
    },
    13: {
      title: "Class 13",
      title1: "Data Processing and Analysis",
      objectives: [
        "Process field data using GIS",
        "Analyze terrain features",
        "Implement CAD workflows",
        "Generate digital terrain models",
      ],
      content: [
        "Data cleaning techniques",
        "Contour generation methods",
        "Surface analysis workflows",
        "Volume calculation procedures",
        "Quality control checks",
      ],
      practical: "Computer-based data processing",
      assessments: [
        { icon: faClipboardCheck, label: "Practical test" },
        { icon: faEye, label: "Process observation" },
      ],
      type: "practical",
    },
    14: {
      title: "Class 14",
      title1: "Final Map Production",
      objectives: [
        "Integrate processed data into final maps",
        "Apply cartographic design principles",
        "Produce presentation-quality outputs",
        "Verify map accuracy and completeness",
      ],
      content: [
        "Map layout design",
        "Scale and legend creation",
        "Topographic symbol placement",
        "Annotation and labeling standards",
        "Final quality assurance checks",
      ],
      practical: "Complete topographical map compilation",
      assessments: [
        { icon: faPen, label: "Written exam" },
        { icon: faFileAlt, label: "Map submission" },
        { icon: faClipboardCheck, label: "Practical evaluation" },
      ],
      type: "assessment",
    },
  },
  stats: {
    classes: 14,
    weeks: 7,
    categories: 4,
    exercises: "14+",
  },
  gradient: "linear-gradient(135deg, #2ecc71, #27ae60)",
  icon: faFileAlt,
  modules: 7,
  hours: 28,
  category: "Topographical Survey",
};
